/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace AuthentiChain {
  export type ProductStruct = {
    id: BigNumberish;
    currentOwner: AddressLike;
    isSold: boolean;
    metadataHash: BytesLike;
    registeredAt: BigNumberish;
  };

  export type ProductStructOutput = [
    id: bigint,
    currentOwner: string,
    isSold: boolean,
    metadataHash: string,
    registeredAt: bigint
  ] & {
    id: bigint;
    currentOwner: string;
    isSold: boolean;
    metadataHash: string;
    registeredAt: bigint;
  };

  export type TransferStruct = {
    from: AddressLike;
    to: AddressLike;
    timestamp: BigNumberish;
  };

  export type TransferStructOutput = [
    from: string,
    to: string,
    timestamp: bigint
  ] & { from: string; to: string; timestamp: bigint };
}

export interface AuthentiChainInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getProduct"
      | "getTransferHistory"
      | "markAsSold"
      | "metadataHashExists"
      | "products"
      | "registerProduct"
      | "totalProducts"
      | "transferHistory"
      | "transferProduct"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "ProductRegistered"
      | "ProductSold"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getProduct",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTransferHistory",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "markAsSold",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "metadataHashExists",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "products",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerProduct",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalProducts",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferHistory",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferProduct",
    values: [BigNumberish, AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "getProduct", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTransferHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "markAsSold", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "metadataHashExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "products", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerProduct",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalProducts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferProduct",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [
    productId: BigNumberish,
    from: AddressLike,
    to: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    productId: bigint,
    from: string,
    to: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    productId: bigint;
    from: string;
    to: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProductRegisteredEvent {
  export type InputTuple = [
    productId: BigNumberish,
    manufacturer: AddressLike,
    metadataHash: BytesLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    productId: bigint,
    manufacturer: string,
    metadataHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    productId: bigint;
    manufacturer: string;
    metadataHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProductSoldEvent {
  export type InputTuple = [
    productId: BigNumberish,
    retailer: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    productId: bigint,
    retailer: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    productId: bigint;
    retailer: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AuthentiChain extends BaseContract {
  connect(runner?: ContractRunner | null): AuthentiChain;
  waitForDeployment(): Promise<this>;

  interface: AuthentiChainInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getProduct: TypedContractMethod<
    [productId: BigNumberish],
    [AuthentiChain.ProductStructOutput],
    "view"
  >;

  getTransferHistory: TypedContractMethod<
    [productId: BigNumberish],
    [AuthentiChain.TransferStructOutput[]],
    "view"
  >;

  markAsSold: TypedContractMethod<
    [productId: BigNumberish],
    [void],
    "nonpayable"
  >;

  metadataHashExists: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  products: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, boolean, string, bigint] & {
        id: bigint;
        currentOwner: string;
        isSold: boolean;
        metadataHash: string;
        registeredAt: bigint;
      }
    ],
    "view"
  >;

  registerProduct: TypedContractMethod<
    [metadataHash: BytesLike],
    [bigint],
    "nonpayable"
  >;

  totalProducts: TypedContractMethod<[], [bigint], "view">;

  transferHistory: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, string, bigint] & { from: string; to: string; timestamp: bigint }
    ],
    "view"
  >;

  transferProduct: TypedContractMethod<
    [productId: BigNumberish, to: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getProduct"
  ): TypedContractMethod<
    [productId: BigNumberish],
    [AuthentiChain.ProductStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTransferHistory"
  ): TypedContractMethod<
    [productId: BigNumberish],
    [AuthentiChain.TransferStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "markAsSold"
  ): TypedContractMethod<[productId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "metadataHashExists"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "products"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, boolean, string, bigint] & {
        id: bigint;
        currentOwner: string;
        isSold: boolean;
        metadataHash: string;
        registeredAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerProduct"
  ): TypedContractMethod<[metadataHash: BytesLike], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "totalProducts"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferHistory"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, string, bigint] & { from: string; to: string; timestamp: bigint }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferProduct"
  ): TypedContractMethod<
    [productId: BigNumberish, to: AddressLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ProductRegistered"
  ): TypedContractEvent<
    ProductRegisteredEvent.InputTuple,
    ProductRegisteredEvent.OutputTuple,
    ProductRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "ProductSold"
  ): TypedContractEvent<
    ProductSoldEvent.InputTuple,
    ProductSoldEvent.OutputTuple,
    ProductSoldEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(uint256,address,address,uint256)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ProductRegistered(uint256,address,bytes32,uint256)": TypedContractEvent<
      ProductRegisteredEvent.InputTuple,
      ProductRegisteredEvent.OutputTuple,
      ProductRegisteredEvent.OutputObject
    >;
    ProductRegistered: TypedContractEvent<
      ProductRegisteredEvent.InputTuple,
      ProductRegisteredEvent.OutputTuple,
      ProductRegisteredEvent.OutputObject
    >;

    "ProductSold(uint256,address,uint256)": TypedContractEvent<
      ProductSoldEvent.InputTuple,
      ProductSoldEvent.OutputTuple,
      ProductSoldEvent.OutputObject
    >;
    ProductSold: TypedContractEvent<
      ProductSoldEvent.InputTuple,
      ProductSoldEvent.OutputTuple,
      ProductSoldEvent.OutputObject
    >;
  };
}
