/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AuthentiChain } from "./AuthentiChain";
export * as factories from "./factories";
export { AuthentiChain__factory } from "./factories/AuthentiChain__factory";
